# -*- coding: utf-8 -*-
"""python-kadai-Akimoto.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vnoWT9g3ZAfkrH_qtSRG9p0xm1Zj23w6

Q1
"""

# 答えは３

"""Q2"""

# 答えは２

"""Q3"""

def greeting(names):
  result=[]
  for a in names:
   if len(a) % 2 == 0:
     result.append("Good morning")
   else:
     result.append("Good night")
  return result

names = ["Myung", "Petrucci", "LaBrie", "Rudess"]
greeting(names)

"""Q4"""

def get_even_number(numbers):
 result = []
 for a in numbers:
   if a % 2 == 0:
     result.append(a)
 return result

numbers = [1,2,3,4,5,6,7,8,9,10]
get_even_number(numbers=numbers)

"""Q5"""

rects = [
[2.1, 4.1],
[0.5, 1.1],
[2.5, 3.2],
]

def get_largest_rect(rects):
  max_area = 0
  max_count = 0
  count = -1
  for a,b in rects:
   area = a * b
   count += 1
   if area > max_area:
     max_area = area
     max_count = count
  return(max_count)

get_largest_rect(rects)

"""Q6"""

def coin_toss(N, x):

 fac1 = 1
 for a in range(N, 0, -1):
     fac1 = fac1 * a
 
 fac2 = 1
 for b in range(N-x, 0, -1):
     fac2 = fac2 * b

 fac3 = 1
 for c in range(x, 0, -1):
     fac3 = fac3 * c
 
 P = fac1 / (fac2*fac3) * (0.1**x) * (0.9**(N-x))

 return round(P, 4)

coin_toss(N=10, x=1)

"""Q7"""

num_list = [5,4,3,2,1]

def bubble_sort(num_list):

 n = len(num_list)
 for a in range(n):
    for b in range(0, n - a - 1):
        if num_list[b] > num_list[b + 1]:
            num_list[b], num_list[b + 1] = num_list[b + 1], num_list[b]

 return num_list

bubble_sort(num_list)